version: '3'
services:

  lldap:
    image: nitnelave/lldap:stable
    ports:
      # For LDAP
      - "3890:3890"
      # For LDAPS
      - "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - "lldap-data:/data"
    environment:
      #- UID=####
      #- GID=####
      #- TZ=####/####
      - LLDAP_JWT_SECRET=my-random-jwt-secret
      - LLDAP_LDAP_USER_PASS=my-random-user-password
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
    depends_on:
      - populate-lldap-data

  populate-lldap-data:
    image: busybox
    volumes:
      - "./lldap/:/local-data"
      - "lldap-data:/data"
    command: "sh -c 'cp -va /local-data/* /data/'"

volumes:
  lldap-data:

