version: '3'
services:

  authnz-api:
    #image: authnz-api:latest
    build:
      context: authnz_api
      dockerfile: Dockerfile
      args:
        - APP_NAME=authnz_api
        - HTTP_PROXY
        - NO_PROXY
    ports:
      - "7652:7652"
    volumes:
      - ./authnz_api/:/app/authnz_api/:ro
      - ./lldap/certs/public.crt:/etc/ssl/certs/lldap-s3.crt
      - ./lldap/certs/CAs/ca.crt:/etc/ssl/certs/lldap-s3-ca.crt
      - ./lldap/certs/bundle.crt:/etc/ssl/certs/lldap-s3-bundle.crt
    environment:
      LISTEN_ADDRESS: "0.0.0.0"
      LISTEN_PORT:    "7652"
      DEBUG:
      SSL_CERT_FILE: "/etc/ssl/certs/lldap-s3-bundle.crt"
      SSL_CA_FILE:   "/etc/ssl/certs/lldap-s3-ca.crt"
    working_dir: /app/authnz_api
    command: /app/authnz_api/authnz-api.sh

