version: '3'
services:

  authnz-api:
    #image: authnz-api:latest
    build:
      context: authnz_api
      dockerfile: Dockerfile
      args:
        - APP_NAME=authnz_api
        - HTTP_PROXY
        - NO_PROXY
      target: base-deps
    ports:
      - "7652:7652"
    volumes:
      - ./authnz_api/:/app/authnz_api/:ro
      - ./lldap/certs/public.crt:/etc/ssl/certs/lldap-s3.crt
      - ./lldap/certs/CAs/ca.crt:/etc/ssl/certs/lldap-s3-ca.crt
      - ./lldap/certs/bundle.crt:/etc/ssl/certs/lldap-s3-bundle.crt
      - authnz-db:/db
    environment:
      SERVER_NAME:    "foobar.localdomain"
      LISTEN_ADDRESS: "0.0.0.0"
      LISTEN_PORT:    "7652"
      DEBUG:
      SSL_CERT_FILE: "/etc/ssl/certs/lldap-s3-bundle.crt"
      SSL_CA_FILE:   "/etc/ssl/certs/lldap-s3-ca.crt"
      DB_FILE:       "/db/authnz.db"
      WORKERS_NUM:   "4"
      THREADS_NUM:   "3"
      FLASK_DEBUG:
    working_dir: /app/authnz_api
    command: "/app/authnz_api/authnz-api.sh"
    depends_on:
      - populate-db

  authnz-api-tests:
    #image: authnz-api:latest
    build:
      context: authnz_api
      dockerfile: Dockerfile
      args:
        - APP_NAME=authnz_api
        - HTTP_PROXY
        - NO_PROXY
      target: base-deps
    volumes:
      - ./authnz_api/:/app/authnz_api/:ro
    environment:
      DEBUG:
      AUTHNZ_API_HOST: authnz-api
      NO_PROXY: $NO_PROXY
      no_proxy: $NO_PROXY
      HTTP_PROXY: ""
      HTTPS_PROXY: ""
      http_proxy: ""
      https_proxy: ""
    working_dir: /app/authnz_api
    command: make tests
    depends_on:
      - authnz-api


  populate-db:
    #image: authnz-api:latest
    build:
      context: authnz_api
      dockerfile: Dockerfile
      args:
        - APP_NAME=authnz-db
        - HTTP_PROXY
        - NO_PROXY
    volumes:
      - ./authnz_api/:/app/authnz_api/:ro
      - authnz-db:/db
    environment:
      LISTEN_ADDRESS: "0.0.0.0"
      LISTEN_PORT:    "7652"
      DEBUG:
      SSL_CERT_FILE: "/etc/ssl/certs/lldap-s3-bundle.crt"
      SSL_CA_FILE:   "/etc/ssl/certs/lldap-s3-ca.crt"
      DB_FILE:       "/db/authnz.db"
      SCHEMA_FILE:   "/app/authnz_api/authnz-db/schema-sqlite3.sql"
    working_dir: /app/authnz_api
    command: "sh -c '/app/authnz_api/populate-db.sh ; while [ true ] ; do sleep 1 ; done'"

volumes:
  authnz-db:

