tests: tests-env \
		0000-get-login-csrf \
		0010-login-user \
		0020-logout-user

tests-env:
	env | sort

0000-get-login-csrf:
	./0000-get-login-csrf.sh
0010-login-user:
	./0010-login-user.sh
0020-logout-user:
	./0020-logout-user.sh
